store = {
  cities: [
    { name: "Portland,OR", age: "25-44" },
    { name: "Anchorage, AL", age: "25-44" },
    { name: "Phoenix, AZ", age: "25-44" },
    { name: "Los Angeles,CA", age: "25-44" },
    { name: "San Francisco,CA", age: "25-44" },
    { name: "Coos Bay,OR", age: "25-44" },
    { name: "Baldwin,MI", age: "45-64" },
    { name: "Rocksprings,TX", age: "45-64" },
    { name: "Fresno,CA", age: "Under 18" },
    { name: "BullheadCity,AZ", age: "65+" },
    { name: "Denton,TX", age: "25-44" },
    { name: "Clare,MI", age: "18-24" },
    { name: "State College,PA", age: "18-24" },
    { name: "Koolaupoko,HI", age: "25-44" },
    { name: "Abbot,ME", age: "45-64" },
    { name: "Sarasota,FL", age: "65+" },
    { name: "Hiawassee,GA", age: "65+" },
    { name: "Chicago,IL", age: "25-44" },
    { name: "Miami,FL", age: "25-44" },
    { name: "Georgetown,TX", age: "Under 18" },
    { name: "Joliet,IL", age: "Under 18" },
    { name: "Southport,NC", age: "45-64" },
    { name: "PortAngeles,WA", age: "45-64" },
    { name: "Ogallala,NE", age: "45-64" },
    { name: "Honolulu,HI", age: "25-44" }
  ],
  displayResult: false
};
